site_name: ROMtools
theme:
  name: material
  palette:
    primary: teal
    accent: deep purple

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
nav:
  - Overview: index.md
  - Run Configuration: RunConfiguration.md
  - Rigid Bodies: RigidBody.md
  - Springs and Dampers: SpringDamper.md
  - Boundary Conditions: Forces.md
  - Solver: Solver.md
  - Animation: Animation.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
